spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fruitable #jdbc:mariadb://fruitable.cvjiwbuuly4r.ap-northeast-2.rds.amazonaws.com:3306/fruitable
    username: sa
    password:
    driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
    properties:
      hibernate:
        format_sql: true
        #show_sql: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org.hibernate.sql: debug
#   org.hibernate.type: trace

#springdoc swagger
springdoc:
  api-docs:
    enabled: true #false 지정 시 외부 노출 X
  swagger-ui:
    enabled: true